//SPECIES DETAILS
export const REQUEST_STUDENT_STARTS = 'REQUEST_STUDENT_STARTS';
export const REQUEST_STUDENT_ENDS = 'REQUEST_STUDENT_ENDS';
export const REQUEST_STUDENT_FAILED = 'REQUEST_STUDENT_FAILED';
export const REQUEST_STUDENT_SUCCESS = 'REQUEST_STUDENT_SUCCESS';
export const REQUEST_STUDENT_FETCH = 'REQUEST_STUDENT_FETCH';
export const REQUEST_STUDENT_REMOVE = 'REQUEST_STUDENT_REMOVE';
export const RESET_STATE = 'RESET_STATE';

// Show students
export const LIST_STUDENT_STARTS = 'LIST_STUDENT_STARTS';
export const LIST_STUDENT_ENDS = 'LIST_STUDENT_ENDS';
export const LIST_STUDENT_FAILED = 'LIST_STUDENT_FAILED';
export const LIST_STUDENT_SUCCESS = 'LIST_STUDENT_SUCCESS';
export const LIST_STUDENT_FETCH = 'LIST_STUDENT_FETCH';

// details
export const DETAILS_STUDENT_STARTS = 'DETAILS_STUDENT_STARTS';
export const DETAILS_STUDENT_ENDS = 'DETAILS_STUDENT_ENDS';
export const DETAILS_STUDENT_FAILED = 'DETAILS_STUDENT_FAILED';
export const DETAILS_STUDENT_SUCCESS = 'DETAILS_STUDENT_SUCCESS';
export const DETAILS_STUDENT_FETCH = 'DETAILS_STUDENT_FETCH';
